### ISSUE TITLE
Which image to pull from Docker hub

### ISSUE THREAD

**Issue by ChristineFarrugia** [MS-PINPOINT/mindGlide#29]
Hi,

Could you kindly clarify which image we should pull from Docker hub? Is it armaneshaghi/mind-glide or mspinpoint/mindglide?

Thanks in advance,
Christine

**Comment by phiphi0815** [comment]
Hi Christine,

Currently we suggest to use the Docker image mspinpoint/mindglide and the command 
```
docker run -it --rm --gpus all -v "{path/to/input/directory/}:/mnt" mspinpoint/mindglide:may2024 {your_file}.nii.gz
```

**Comment by ChristineFarrugia** [comment]
Many thanks. I take it this is also the image to pull if we want to use Apptainer? I'm building the Apptainer .sif file like so:
`apptainer build ${APPTAINER_TMPDIR}/mindglide.sif docker://mspinpoint/mindglide:may2024`

**Comment by ChristineFarrugia** [comment]
Many thanks. I take it this is also the image to pull if we want to use Apptainer? I'm building the Apptainer .sif file like so:

`apptainer build ${APPTAINER_TMPDIR}/mindglide.sif docker://mspinpoint/mindglide:may2024`

**Comment by phiphi0815** [comment]
We have not yet tested the apptainer version of the latest update.

If you want to use apptainer instead of the docker version mentioned above, we currently refer to our initial [guide](https://github.com/MS-PINPOINT/mindGlide?tab=readme-ov-file#with-apptainer-singularity) on how to build MindGlide with apptainer (singularity). This uses an older version, where we tested the usage with apptainer.

`#running from the same directory as the image
singularity run --nv \
--bind $PWD:/mnt \
/path/to/mind-glide_latest.sif flair.nii.gz`
